### PR TITLE
S-expression reader.

### PR DESCRIPTION
**Pull request by mwkmwkmwk**
This change is [Reviewable](https://reviewable.io/reviews/koriakin/binflakes/7)

### CODE REVIEW

**Comment by mkow** [comment]
Reviewed 5 of 19 files at r1, 5 of 6 files at r2, 5 of 7 files at r3.
Review status: 15 of 17 files reviewed at latest revision, all discussions resolved.

---

*[binflakes/sexpr/location.py, line 20 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5kbSNeCiXtYtHPVrvk:-L5kbSNf8fNO8t8vsQul:bprcscz) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/location.py#L20)):*
> ```Python
>         given two single locations.
>         """
>         return TextLocationRange(
> ```

Maybe add an assert for `self.filename == other.filename` ? Seems safer this way.
Same for a reversed range.

---

*[binflakes/sexpr/location.py, line 28 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5kbngj8OtxOljABVdn:-L5kbngj8OtxOljABVdo:bck84v9) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/location.py#L28)):*
> ```Python
> @attrs(slots=True)
> class TextLocationRange:
>     """Represents a range of locations in the input."""
> ```

`in the input` -> `in one input file`

---

*[binflakes/sexpr/nodes.py, line 14 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5kg7-t-1Cg7Z42Eaa8:-L5kg7-t-1Cg7Z42Eaa9:bye6ye2) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/nodes.py#L14)):*
> ```Python
> 
> 
> def _location_attr():
> ```

I'd prefer `_attrib`, to be consistent with `attrib()`. There's already `attr.attrs`, let's not confuse the reader more ;)

---

*[binflakes/sexpr/nodes.py, line 23 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5knE0oEAzLJ0xS5Gli:-L5knE0oEAzLJ0xS5Glj:b4mzj48) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/nodes.py#L23)):*
> ```Python
> 
> @attrs(slots=True)
> class NodeList(Node):
> ```

`NodeList` -> `ListNode` (same for other classes)

---

*[binflakes/sexpr/nodes.py, line 120 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5kjXReEKmh8dohSiYs:-L5kjXReEKmh8dohSiYt:bny182k) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/nodes.py#L120)):*
> ```Python
> 
> def make_node(val, loc=None):
>     """Converts a bare python value to a corresponding Node, recursively
> ```

`python` -> `Python`

---

*[binflakes/sexpr/string.py, line 34 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5ktFZgEDSJ3FoGM7Lj:-L5ktFZgEDSJ3FoGM7Lk:b-xskwa9) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/string.py#L34)):*
> ```Python
>             res.write(f'\\u{ord(c):04x}')
>         else:
>             res.write(f'\\U{ord(c):06x}')
> ```

`assert ord(c) < 0x1000000`

---

*[tests/sexpr/test_string.py, line 8 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5l-1U-0zJuA54oud0_:-L5l-1U-0zJuA54oud0a:b-2p9m9x) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/tests/sexpr/test_string.py#L8)):*
> ```Python
> class TestString:
>     @pytest.mark.parametrize(('orig', 'escaped'), [
>         ('abc', '"abc"'),
> ```

Add an empty string.

---

*[tests/sexpr/test_symbol.py, line 6 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5l2J_QE4PiM7X4OS7k:-L5l2J_QE4PiM7X4OS7l:bh9qnme) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/tests/sexpr/test_symbol.py#L6)):*
> ```Python
> class TestSymbol:
>     def test_symbol(self):
>         a = Symbol('abc')
> ```

Random thought: should we accept an empty name for a symbol?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/koriakin/binflakes/7)*

**Comment by mwkmwkmwk** [comment]
Review status: 11 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[binflakes/sexpr/location.py, line 20 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5kbSNeCiXtYtHPVrvk:-L5l4NQhffF6EhhHNTkb:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/location.py#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe add an assert for `self.filename == other.filename` ? Seems safer this way.
Same for a reversed range.
</blockquote></details>

Done.

---

*[binflakes/sexpr/location.py, line 28 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5kbngj8OtxOljABVdn:-L5l4NvNTnBVd6vajqTq:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/location.py#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`in the input` -> `in one input file`
</blockquote></details>

Done.

---

*[binflakes/sexpr/nodes.py, line 14 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5kg7-t-1Cg7Z42Eaa8:-L5l4ZYo-Rokt-hgHlXY:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/nodes.py#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer `_attrib`, to be consistent with `attrib()`. There's already `attr.attrs`, let's not confuse the reader more ;)
</blockquote></details>

Done.

---

*[binflakes/sexpr/nodes.py, line 23 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5knE0oEAzLJ0xS5Gli:-L5l5JbZwH6miWCuOD6h:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/nodes.py#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`NodeList` -> `ListNode` (same for other classes)
</blockquote></details>

Done.

---

*[binflakes/sexpr/nodes.py, line 120 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5kjXReEKmh8dohSiYs:-L5l5JNx9QkfwPZKedDA:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/nodes.py#L120)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`python` -> `Python`
</blockquote></details>

Done.

---

*[binflakes/sexpr/string.py, line 34 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5ktFZgEDSJ3FoGM7Lj:-L5l3Ur1Dc6XCJOpjQw7:bfjyepf) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/binflakes/sexpr/string.py#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`assert ord(c) < 0x1000000`
</blockquote></details>

Redundant -- Python strings cannot ever hold codepoints >= 0x110000.

---

*[tests/sexpr/test_string.py, line 8 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5l-1U-0zJuA54oud0_:-L5l6VmKm0NMgQoZrpBO:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/tests/sexpr/test_string.py#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Add an empty string.
</blockquote></details>

Done.

---

*[tests/sexpr/test_symbol.py, line 6 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5l2J_QE4PiM7X4OS7k:-L5l3pey1NnPGk95t3dF:bfodm6m) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/tests/sexpr/test_symbol.py#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Random thought: should we accept an empty name for a symbol?
</blockquote></details>

Definitely no (no way to make an empty token).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/7)*

**Comment by mkow** [comment]
Reviewed 1 of 19 files at r1, 3 of 6 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[binflakes/sexpr/location.py, line 18 at r5](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5yiL6iCHwalbQIAFSm:-L5yiL6iCHwalbQIAFSn:bmb58rw) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/binflakes/sexpr/location.py#L18)):*
> ```Python
>     def __sub__(self, other):
>         """Returns a TextLocationRange corresponding to the range between
>         given two single locations.
> ```

Could you add a comment that it translates `[)` range to `[]` ?

---

*[binflakes/sexpr/read.py, line 195 at r5](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5yillp59nY6m-MEZv8:-L5yillp59nY6m-MEZv9:be7ukk9) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/binflakes/sexpr/read.py#L195)):*
> ```Python
>                 elif match['rparen'] is not None:
>                     if not self.stack:
>                         raise ReadError(f'{loc}: unmatched close paren')
> ```

`close paren` -> `closing paren`

---

*[binflakes/sexpr/read.py, line 265 at r5](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5ykljR3tTzq2vnXiIk:-L5ykljSCPPUXarPK3mm:b-wno10q) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/binflakes/sexpr/read.py#L265)):*
> ```Python
>                     self.string_buffer.write(chr(code))
>                 else:
>                     assert 0
> ```

Are you sure this state can't be reached? e.g. using `\xX`?

---

*[tests/sexpr/test_read.py, line 137 at r5](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5t1nni4W5xNCQr0Jvl:-L5t1nni4W5xNCQr0Jvm:b-funtlb) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/tests/sexpr/test_read.py#L137)):*
> ```Python
>             SymbolNode(Symbol('ghi')),
>         ]),
>         ('(abc def (ghi ##jkl) ##(mno ## pqr stq) uvw)', [
> ```

Could you also add a test for single-line comments?

---

*[tests/sexpr/test_symbol.py, line 6 at r3](https://beta.reviewable.io/reviews/koriakin/binflakes/7#-L5l2J_QE4PiM7X4OS7k:-L5shpn2E-zeyvtuA0bN:b-biasv) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/tests/sexpr/test_symbol.py#L6)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

Definitely no (no way to make an empty token).
</blockquote></details>

So, maybe it would be a good idea to add an assert for this in `Symbol.__init__`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/koriakin/binflakes/7)*

**Comment by mwkmwkmwk** [comment]
Review status: 12 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[binflakes/sexpr/location.py, line 18 at r5](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5yiL6iCHwalbQIAFSm:-L5yvnRpXofTMXabCR-c:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/binflakes/sexpr/location.py#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a comment that it translates `[)` range to `[]` ?
</blockquote></details>

Done.

---

*[binflakes/sexpr/read.py, line 195 at r5](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5yillp59nY6m-MEZv8:-L5yvsTXPrlDN5B24T7_:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/binflakes/sexpr/read.py#L195)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`close paren` -> `closing paren`
</blockquote></details>

Done.

---

*[binflakes/sexpr/read.py, line 265 at r5](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5ykljR3tTzq2vnXiIk:-L5yw2CQzDTL2wq2n8iu:b3akmcs) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/binflakes/sexpr/read.py#L265)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are you sure this state can't be reached? e.g. using `\xX`?
</blockquote></details>

No -- if we get here, the regex matched (otherwise we fail in the "if not match" branch above), so one of the alternative groups has to be non-empty. Also, the tests already cover "\x1z", "\d", and some other invalid escape sequences.

---

*[tests/sexpr/test_read.py, line 137 at r5](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5t1nni4W5xNCQr0Jvl:-L5yzWpMqe87DGtkKqmB:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/b92cab7d2ac99c8109be599f26f4a42bbf610e1a/tests/sexpr/test_read.py#L137)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you also add a test for single-line comments?
</blockquote></details>

Done.

---

*[tests/sexpr/test_symbol.py, line 6 at r3](https://reviewable.io:443/reviews/koriakin/binflakes/7#-L5l2J_QE4PiM7X4OS7k:-L5yzWEV12X9kFsCZw3z:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/4b4e981363907c90d69b8e9583372f168a3665e6/tests/sexpr/test_symbol.py#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, maybe it would be a good idea to add an assert for this in `Symbol.__init__`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/7)*

**Comment by mkow** [comment]
Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/koriakin/binflakes/7)*

**Pull request merged**
