### PR TITLE
Add the BinArray type.

### PR DESCRIPTION
**Pull request by mwkmwkmwk**
This change is [Reviewable](https://reviewable.io/reviews/koriakin/binflakes/3)

### CODE REVIEW

**Comment by mkow** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[binflakes/types/array.py, line 34 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L55vovRqU_VbpJCLs-8:-L55vovRqU_VbpJCLs-9:bu8wlcm) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L34)):*
> ```Python
>         - ``BinArray(bytes or bytearray)``: creates a BinArray of width 8
>           with items from the given bytearray.
>         - ``BinArray(width)``: creates empty BinArray of given width.
> ```

I'd prefer to force a user to use named params for `width` and `length`, it may be quite unintuitive when reading code. At first I though that `BinArray(12)` means a BinArray of size 12, but this didn't make any sense. This is probably because of my intuitions from C++'s `std::vector` and Python's `bytearray`.

---

*[binflakes/types/array.py, line 121 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56FhNg9ybgkA5Vk657:-L56FhNg9ybgkA5Vk658:b-480xbk) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L121)):*
> ```Python
>             if idx < 0:
>                 idx += len(self)
>             if idx not in range(len(self)):
> ```

Hmm, this looks like a potential performance problem. Isn't `bin_array[:]` O(n^2) now? Is it some python3 magic here I'm not aware about?

---

*[binflakes/types/array.py, line 133 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56JT9csEg0VI2APTht:-L56JT9duTHFjNFVs9_T:b-ref8zs) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L133)):*
> ```Python
>         a BinWord instance of the same width as the array, or an int
>         or BinInt instance that will be automatically converted
>         to BinWord.
> ```

It would be nice to say here what happens when the int or BinInt doesn't fit in the width.

---

*[binflakes/types/array.py, line 150 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56KVtDhm-vRe9mnfMs:-L56KVtEzkTTO5q03AVl:b-7ropln) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L150)):*
> ```Python
>             if idx < 0:
>                 idx += len(self)
>             if idx not in range(len(self)):
> ```

ditto

---

*[binflakes/types/array.py, line 158 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56Lc8J5wP4pfn4Ars9:-L56Lc8J5wP4pfn4ArsA:b2owqbf) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L158)):*
> ```Python
>             raw = self._data[sbyte:ebyte]
>             raw = BinInt.from_bytes(raw, 'little')
>             raw = raw.insert(sbit, val)
> ```

Just noticed: IMO the name of `BinInt.insert` is very misleading - it doesn't insert bits, it overwrites them (which is different that insert's semantic in all common containers).

---

*[binflakes/types/array.py, line 162 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56M6TdGI9N7DNEUTDG:-L56M6TdGI9N7DNEUTDH:b-wfb83n) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L162)):*
> ```Python
> 
>     def __repr__(self):
>         width_hexits = BinInt(self._width).ceildiv(4)
> ```

IMHO 'nibbles' is better, 'hexits' seems to be quite an uncommon name.

---

*[binflakes/types/array.py, line 189 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56NWDxyvHnHqGKARG2:-L56NWDxyvHnHqGKARG3:bvm1wx8) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L189)):*
> ```Python
>         if self._len != other._len:
>             return False
>         return self._data == other._data
> ```

This may turn into a bug after implementing `pop` or `remove` - the last byte may contain some unused padding bits with garbage then (depending on the implementation of those methods).

---

*[tests/types/test_array.py, line 194 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L560A79zgEyK68hJZhB:-L560A79zgEyK68hJZhC:bb5gbp8) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/tests/types/test_array.py#L194)):*
> ```Python
>         t = BinArray(13, [0x123, 0x456, 0x789, 0xabc, 0xdef])
>         a = t[:]
>         a[1:3] = BinArray(13, [0x1234, 0x1567])
> ```

Could you also test here whether `t[:]` really created a copy of `t`? (instead of returning an alias to `t`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mwkmwkmwk** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[binflakes/types/array.py, line 34 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L55vovRqU_VbpJCLs-8:-L57hP01FXr72bQjdefL:b-clmp7m) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to force a user to use named params for `width` and `length`, it may be quite unintuitive when reading code. At first I though that `BinArray(12)` means a BinArray of size 12, but this didn't make any sense. This is probably because of my intuitions from C++'s `std::vector` and Python's `bytearray`.
</blockquote></details>

```BinArray(data=[], *, width=None, length=None)```? (with width only optional if created from a bytearray)
```


---

*[binflakes/types/array.py, line 121 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56FhNg9ybgkA5Vk657:-L57fajr_fcZMtbNUAv2:bhdsl52) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L121)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, this looks like a potential performance problem. Isn't `bin_array[:]` O(n^2) now? Is it some python3 magic here I'm not aware about?
</blockquote></details>

range is quite a smart class in Python 3, and this is O(1) (and if we end up porting code to py2, ```from six import range```.

---

*[binflakes/types/array.py, line 158 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56Lc8J5wP4pfn4Ars9:-L57hsy7a-b05L7pYv6s:b-98lb1y) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L158)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just noticed: IMO the name of `BinInt.insert` is very misleading - it doesn't insert bits, it overwrites them (which is different that insert's semantic in all common containers).
</blockquote></details>

Ok, can you suggest another name? I've seen "merge" used as well

---

*[binflakes/types/array.py, line 189 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56NWDxyvHnHqGKARG2:-L57iK5n3Caup1Na_z15:bs5vepm) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L189)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This may turn into a bug after implementing `pop` or `remove` - the last byte may contain some unused padding bits with garbage then (depending on the implementation of those methods).
</blockquote></details>

Correct, but the intention is to keep the padding bits set to 0 at all times. I'll document it in the _init docstring. I suppose we could do it either way for BinArray, but let's be consistent with the (upcoming) C implementations of BinInt & BinWord, which really want the padding set consistently.

---

*[tests/types/test_array.py, line 194 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L560A79zgEyK68hJZhB:-L57gVBhElqUOgKFYDAV:b-yj9otb) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/tests/types/test_array.py#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you also test here whether `t[:]` really created a copy of `t`? (instead of returning an alias to `t`)
</blockquote></details>

This is covered in test_getslice (a[:] is not a)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*
<!-- Sent from Reviewable.io -->

**Comment by mwkmwkmwk** [comment]
*[binflakes/types/array.py, line 189 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56NWDxyvHnHqGKARG2:-L57mzMFlyJBwTODLEcH:bdbxqor) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L189)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

Correct, but the intention is to keep the padding bits set to 0 at all times. I'll document it in the _init docstring. I suppose we could do it either way for BinArray, but let's be consistent with the (upcoming) C implementations of BinInt & BinWord, which really want the padding set consistently.
</blockquote></details>

Also, this bug is going to be trivially caught by an obvious test:

```
a = BinArray(4, [1, 2, 3, 4])
a.pop()
assert a == BinArray(4, [1, 2, 3])
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mwkmwkmwk** [comment]
*[binflakes/types/array.py, line 34 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L55vovRqU_VbpJCLs-8:-L57ovj5HNWp_58WeNch:b-6iw3hb) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L34)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

```BinArray(data=[], *, width=None, length=None)```? (with width only optional if created from a bytearray)
</blockquote></details>

Also, my concern here is providing a reasonably short repr()...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mwkmwkmwk** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[binflakes/types/array.py, line 34 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L55vovRqU_VbpJCLs-8:-L586ESSlVfLsK0NY7tb:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L34)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

Also, my concern here is providing a reasonably short repr()...
</blockquote></details>

Done.

---

*[binflakes/types/array.py, line 133 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56JT9csEg0VI2APTht:-L587Ezm5LjmCQIyU4og:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L133)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It would be nice to say here what happens when the int or BinInt doesn't fit in the width.
</blockquote></details>

Done.

---

*[binflakes/types/array.py, line 162 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56M6TdGI9N7DNEUTDG:-L587G28kRmD8cqf0P9a:b-896fix) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L162)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMHO 'nibbles' is better, 'hexits' seems to be quite an uncommon name.
</blockquote></details>

Done.

---

*[binflakes/types/array.py, line 189 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56NWDxyvHnHqGKARG2:-L587TqWqMxXvWM5SDfB:bg9tohb) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L189)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

Also, this bug is going to be trivially caught by an obvious test:

```
a = BinArray(4, [1, 2, 3, 4])
a.pop()
assert a == BinArray(4, [1, 2, 3])
```
</blockquote></details>

Documented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mkow** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[binflakes/types/array.py, line 34 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L55vovRqU_VbpJCLs-8:-L5Dz45xIsaqBJC6h3Bg:bb6ywmx) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L34)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[binflakes/types/array.py, line 121 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56FhNg9ybgkA5Vk657:-L5DzrUHb0BNlL20Gz7T:bltbbbh) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L121)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

range is quite a smart class in Python 3, and this is O(1) (and if we end up porting code to py2, ```from six import range```.
</blockquote></details>

Is this behavior documented anywhere? I did some tests with `timeit` and it really seems to be not-that-slow, but can't find any guarantee in the docs.

---

*[binflakes/types/array.py, line 158 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56Lc8J5wP4pfn4Ars9:-L5E-Xg0FOGA8BhHrrjl:b-i07cbz) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L158)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

Ok, can you suggest another name? I've seen "merge" used as well
</blockquote></details>

I've never seen `merge` used in such cases (we are not "merging" data, the old bits are always overwritten). Some ideas:
- `set_bits_at`
- `overwrite_bits`
- `replace_bits`

They are quite long, but IMO much less misleading. Any thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mwkmwkmwk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[binflakes/types/array.py, line 121 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56FhNg9ybgkA5Vk657:-L5ED30LHpK3foTkcKUS:b-eyof7y) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L121)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this behavior documented anywhere? I did some tests with `timeit` and it really seems to be not-that-slow, but can't find any guarantee in the docs.
</blockquote></details>

https://docs.python.org/3/library/stdtypes.html#typesseq-range

"Changed in version 3.2: Implement the Sequence ABC. Support slicing and negative indices. Test int objects for membership in constant time instead of iterating through all items."

---

*[binflakes/types/array.py, line 158 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56Lc8J5wP4pfn4Ars9:-L5EDc5vMvZFLDtJaQzT:bdzhyz2) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L158)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I've never seen `merge` used in such cases (we are not "merging" data, the old bits are always overwritten). Some ideas:
- `set_bits_at`
- `overwrite_bits`
- `replace_bits`

They are quite long, but IMO much less misleading. Any thoughts?
</blockquote></details>

Well, it may be confusing, but it's consistent with usage in CPU instruction sets -- it's called insert in most CPUs that have it.

Would it help if we called them eg. bf_insert and bf_extract?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mkow** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[binflakes/types/array.py, line 158 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56Lc8J5wP4pfn4Ars9:-L5LfmwnLrl1UHojwesS:b-q79si) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L158)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

Well, it may be confusing, but it's consistent with usage in CPU instruction sets -- it's called insert in most CPUs that have it.

Would it help if we called them eg. bf_insert and bf_extract?
</blockquote></details>

IMO our priority should be to not confuse the reader, even at the cost of not using "standard" terms (because in this case they are standard only for some narrow groups of readers).
This naming may be standard in some CPU instructions (and probably only there), but we'll use this library for more things than just disassemblers. Also, this class does not mention CPUs/assembly anywhere, so even if the reader knows about this convention in CPUs they may misunderstand the code.

I don't like `bf_insert`, it still have that "insert" in it. IMO `set_bits_at` is better, it's not much longer and its semantic is clear after reading this name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mwkmwkmwk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[binflakes/types/array.py, line 158 at r1](https://reviewable.io:443/reviews/koriakin/binflakes/3#-L56Lc8J5wP4pfn4Ars9:-L5LlfzlH_2OPg1c52PE:b-m8boiz) ([raw file](https://github.com/koriakin/binflakes/blob/009071dae9bd50a84a7a8d43d5515a237a8f6fbf/binflakes/types/array.py#L158)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO our priority should be to not confuse the reader, even at the cost of not using "standard" terms (because in this case they are standard only for some narrow groups of readers).
This naming may be standard in some CPU instructions (and probably only there), but we'll use this library for more things than just disassemblers. Also, this class does not mention CPUs/assembly anywhere, so even if the reader knows about this convention in CPUs they may misunderstand the code.

I don't like `bf_insert`, it still have that "insert" in it. IMO `set_bits_at` is better, it's not much longer and its semantic is clear after reading this name.
</blockquote></details>

alright, we'll go with deposit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Comment by mkow** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/koriakin/binflakes/3)*

**Pull request merged**
